import { DEFAULT_CHILD_AGENT_SETTINGS, DEFAULT_CLAUDE_MODEL, DEFAULT_CURSOR_MODEL, DEFAULT_OPENAI_MODEL } from "./appConfig";
import type { TaskStatus } from "./taskStore";
import type { AppSettings, ChildAgentSettings, ChildAgentTarget, PermissionMode, Project, ProjectSubagentSettings, Provider } from "../types";
import type { ReasoningEffort } from "../components/ModelPowerControl";

/**
 * Cross-provider sub-agents.
 *
 * A root agent may only delegate to destinations the user approved, and the
 * approved set is frozen into a per-thread policy the moment the root thread
 * starts. Everything in this module is pure so the routing, readiness, and
 * migration rules can be exercised without a runtime.
 */

export const CHILD_AGENT_PROVIDERS: Provider[] = ["openai", "openrouter", "claude", "cursor"];

/** Mirrors the backend ceiling in `agents.rs`. */
export const MAX_CHILD_AGENT_TARGETS = 24;
/**
 * Most children one thread may run at once. Numerically the same as the
 * destination ceiling today, but a different rule: a roster of destinations is
 * a menu, while concurrency is a live budget.
 */
export const MAX_SUBAGENT_CONCURRENCY = 24;
export const CHILD_AGENT_REASONING_EFFORTS: ReasoningEffort[] = ["low", "medium", "high", "xhigh", "max", "ultra"];

export { DEFAULT_CHILD_AGENT_SETTINGS };

/** Runtime readiness of every provider OpenKiwi can start a child on. */
export interface ChildAgentReadiness {
  codexRuntimeAvailable: boolean;
  openAiSignedIn: boolean;
  openRouterReady: boolean;
  claudeReady: boolean;
  cursorReady: boolean;
}

/** The frozen delegation policy a root thread carries for its whole life. */
export interface ChildAgentPolicy {
  /**
   * Identity of the backend bridge session. Generated by OpenKiwi rather than
   * taken from the thread, because for app-server providers the bridge has to
   * be configured before `thread/start` reports the id it belongs to.
   */
  sessionId: string;
  /** Empty until the runtime reports the thread this session belongs to. */
  rootThreadId: string;
  maxConcurrent: number;
  /** Inherited from the root thread; a model can never relax this policy. */
  permission: PermissionMode;
  /** Runtime choices are frozen too, so a background root never inherits the
   * settings of whichever conversation happens to be visible when it spawns. */
  systemPrompt: string;
  projectInstructionsEnabled: boolean;
  reasoningEffort: ReasoningEffort;
  serviceTier: string | null;
  targets: ChildAgentTarget[];
  capturedAt: number;
}

/** Parent/child ownership, persisted so it survives a reload. */
export interface ChildAgentLink {
  childThreadId: string;
  rootThreadId: string;
  /** Bridge session that spawned this child; its concurrency slot owner. */
  sessionId: string;
  targetId: string;
  provider: Provider;
  model: string;
  reasoningEffort: ReasoningEffort;
  title: string;
  createdAt: number;
  /** Persisted once the child settles so reloads never invent an outcome. */
  terminalStatus?: "completed" | "cancelled" | "failed";
}

/**
 * Lifecycle word a model reads, kept stable across providers.
 *
 * Lives beside the policy rules rather than in the runtime hook so the UI can
 * describe a child without importing the delegation transport.
 */
export function childLifecycle(status: TaskStatus): string {
  if (status === "completed") return "completed";
  if (status === "interrupted") return "cancelled";
  if (status === "error") return "failed";
  if (status === "starting") return "starting";
  if (status === "running") return "running";
  // A persisted link with no in-memory task is from an earlier app process;
  // no provider turn owned by that process can still hold a live slot.
  return "completed";
}

/** Preserve a persisted outcome when no task from this app process exists. */
export function childLifecycleForLink(link: ChildAgentLink, status: TaskStatus): string {
  if (status !== "idle") return childLifecycle(status);
  // An unterminated link from an earlier process cannot still be running. It
  // was interrupted by that process ending, so cancellation is the only
  // outcome we can assert without fabricating a successful completion.
  return link.terminalStatus ?? "cancelled";
}

export function isChildActive(status: TaskStatus): boolean {
  return status === "starting" || status === "running";
}

export function isReasoningEffort(value: unknown): value is ReasoningEffort {
  return typeof value === "string" && CHILD_AGENT_REASONING_EFFORTS.includes(value as ReasoningEffort);
}

export function reasoningEffortsThrough(maximum: ReasoningEffort): ReasoningEffort[] {
  const end = CHILD_AGENT_REASONING_EFFORTS.indexOf(maximum);
  return CHILD_AGENT_REASONING_EFFORTS.slice(0, Math.max(0, end) + 1);
}

/** Resolve the actual child effort without ever exceeding a user ceiling. */
export function childAgentReasoningEffort(
  target: ChildAgentTarget,
  inherited: ReasoningEffort,
  requested?: unknown,
): ReasoningEffort {
  if (target.reasoningMode === "fixed") return target.reasoningEffort;
  if (target.reasoningMode !== "agent") return inherited;
  const allowed = reasoningEffortsThrough(target.reasoningMaxEffort);
  if (isReasoningEffort(requested) && allowed.includes(requested)) return requested;
  return allowed.includes(inherited) ? inherited : allowed.at(-1) ?? "medium";
}

export function describeChildAgentReasoning(target: ChildAgentTarget): string {
  if (target.reasoningMode === "fixed") return target.reasoningEffort;
  if (target.reasoningMode === "agent") return `Main agent decides · up to ${target.reasoningMaxEffort}`;
  return "Inherit parent";
}

export function providerDisplayName(provider: Provider): string {
  if (provider === "openrouter") return "OpenRouter";
  if (provider === "claude") return "Claude";
  if (provider === "cursor") return "Cursor";
  return "OpenAI";
}

/**
 * Agent-facing destination names are lowercase slugs: they appear verbatim in
 * a tool enum, so they must be stable, short, and free of anything a model
 * could mistake for structure.
 */
export function normalizeChildAgentId(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^[^a-z0-9]+/, "")
    .replace(/-+/g, "-")
    .replace(/-$/, "")
    .slice(0, 40);
}

/**
 * Live-typing variant of {@link normalizeChildAgentId}. It keeps a trailing
 * separator, because stripping it on every keystroke makes a name like
 * "grok fast" impossible to type: the space would vanish before the next
 * letter arrives. The strict form is applied when the destination is added.
 */
export function sanitizeChildAgentIdInput(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^[^a-z0-9]+/, "")
    .replace(/-{2,}/g, "-")
    .slice(0, 40);
}

export function isValidChildAgentId(value: string): boolean {
  return /^[a-z0-9][a-z0-9_-]{0,39}$/.test(value);
}

/** Give a new destination a name that does not collide with an existing one. */
export function uniqueChildAgentId(candidate: string, existing: ChildAgentTarget[]): string {
  const base = normalizeChildAgentId(candidate) || "agent";
  if (!existing.some((target) => target.id === base)) return base;
  for (let suffix = 2; suffix < 100; suffix += 1) {
    const next = `${base.slice(0, 36)}-${suffix}`;
    if (!existing.some((target) => target.id === next)) return next;
  }
  return `${base.slice(0, 32)}-${Date.now().toString(36)}`;
}

/**
 * The model identity a destination actually starts with. An empty model means
 * "whatever this provider defaults to", which keeps a destination working when
 * a provider renames its flagship.
 */
export function childAgentModel(target: Pick<ChildAgentTarget, "provider" | "model">): string {
  const model = target.model.trim();
  if (model) return model;
  if (target.provider === "claude") return DEFAULT_CLAUDE_MODEL;
  if (target.provider === "cursor") return DEFAULT_CURSOR_MODEL;
  if (target.provider === "openrouter") return "";
  return DEFAULT_OPENAI_MODEL;
}

/**
 * Why a destination cannot be used right now, or null when it is usable.
 * Configuration problems (a model that provider cannot address) are reported
 * before authentication problems, because the user has to fix them first.
 */
export function childAgentTargetIssue(
  target: ChildAgentTarget,
  readiness: ChildAgentReadiness,
): string | null {
  if (!CHILD_AGENT_PROVIDERS.includes(target.provider)) return "Unknown provider.";
  const model = childAgentModel(target);
  if (target.provider === "openrouter" && !model.includes("/")) {
    return "OpenRouter needs a fully qualified model, for example `x-ai/grok-4.5`.";
  }
  if (target.provider === "claude" && !model.startsWith("claude-")) {
    return "Claude Code only accepts Claude model identities.";
  }
  if (target.provider === "openai" && (model.includes("/") || model.startsWith("claude-"))) {
    return "That model is not addressable through the OpenAI provider.";
  }
  if (target.provider === "openai" || target.provider === "openrouter") {
    if (!readiness.codexRuntimeAvailable) return "The OpenAI runtime is not installed.";
  }
  if (target.provider === "openai" && !readiness.openAiSignedIn) return "Sign in to ChatGPT first.";
  if (target.provider === "openrouter" && !readiness.openRouterReady) return "Add an OpenRouter API key first.";
  if (target.provider === "claude" && !readiness.claudeReady) return "Install and sign in to Claude Code first.";
  if (target.provider === "cursor" && !readiness.cursorReady) return "Install and sign in to Cursor Agent first.";
  return null;
}

function sanitizeText(value: unknown, limit: number): string {
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, limit) : "";
}

/**
 * Rebuild the roster from persisted (or hand-edited) storage. Anything that
 * could not be honoured later is dropped here rather than at spawn time, and
 * a missing value migrates to the backward-compatible default: delegation off,
 * no destinations.
 */
export function sanitizeChildAgentSettings(stored: unknown): ChildAgentSettings {
  if (!stored || typeof stored !== "object") return { ...DEFAULT_CHILD_AGENT_SETTINGS, targets: [] };
  const value = stored as Record<string, unknown>;
  const seen = new Set<string>();
  const targets: ChildAgentTarget[] = [];
  const candidates = Array.isArray(value.targets) ? value.targets : [];
  for (const candidate of candidates) {
    if (targets.length >= MAX_CHILD_AGENT_TARGETS) break;
    if (!candidate || typeof candidate !== "object") continue;
    const entry = candidate as Record<string, unknown>;
    const provider = entry.provider as Provider;
    if (!CHILD_AGENT_PROVIDERS.includes(provider)) continue;
    const id = normalizeChildAgentId(typeof entry.id === "string" ? entry.id : "");
    if (!isValidChildAgentId(id) || seen.has(id)) continue;
    seen.add(id);
    targets.push({
      id,
      provider,
      model: sanitizeText(entry.model, 128),
      label: sanitizeText(entry.label, 80) || id,
      description: sanitizeText(entry.description, 400),
      // An entry with no explicit flag predates the flag and stays available.
      enabled: entry.enabled !== false,
      // Existing destinations inherit the root effort, preserving the exact
      // behaviour they had before per-destination reasoning existed.
      reasoningMode: entry.reasoningMode === "fixed" || entry.reasoningMode === "agent" ? entry.reasoningMode : "inherit",
      reasoningEffort: isReasoningEffort(entry.reasoningEffort) ? entry.reasoningEffort : "medium",
      reasoningMaxEffort: isReasoningEffort(entry.reasoningMaxEffort) ? entry.reasoningMaxEffort : "high",
    });
  }
  return { enabled: value.enabled === true, targets };
}

/** Sanitize an optional project-local policy; null means inherit global. */
export function sanitizeProjectSubagentSettings(stored: unknown): ProjectSubagentSettings | null {
  if (!stored || typeof stored !== "object") return null;
  const value = stored as Record<string, unknown>;
  return {
    enabled: value.enabled === true,
    maxConcurrent: Math.min(MAX_SUBAGENT_CONCURRENCY, Math.max(1, Math.floor(Number(value.maxConcurrent)) || 1)),
    childAgents: sanitizeChildAgentSettings(value.childAgents),
  };
}

export function projectSubagentSettingsFromApp(settings: Pick<
  AppSettings,
  "subagentsEnabled" | "subagentMax" | "childAgents"
>): ProjectSubagentSettings {
  return {
    enabled: settings.subagentsEnabled,
    maxConcurrent: settings.subagentMax,
    childAgents: sanitizeChildAgentSettings(settings.childAgents),
  };
}

/** Apply a project's complete sub-agent policy, or inherit the app defaults. */
export function settingsWithProjectSubagents(settings: AppSettings, stored: unknown): AppSettings {
  const project = sanitizeProjectSubagentSettings(stored);
  if (!project) return settings;
  return {
    ...settings,
    subagentsEnabled: project.enabled,
    subagentMax: project.maxConcurrent,
    childAgents: project.childAgents,
  };
}

/**
 * A child remains depth-one for its whole lifetime, including later turns the
 * user sends after opening the child as a normal conversation. Without this
 * final thread-level clamp, an OpenRouter resume or a new Claude Code process
 * could reapply the project's root-agent policy and expose native delegation.
 */
export function settingsWithoutChildDelegation(settings: AppSettings): AppSettings {
  if (!settings.subagentsEnabled && !settings.childAgents.enabled && settings.subagentMax === 1) return settings;
  return {
    ...settings,
    subagentsEnabled: false,
    subagentMax: 1,
    childAgents: { enabled: false, targets: [] },
  };
}

/** Migrate persisted project policies without inventing overrides for projects that inherit. */
export function sanitizeProjectSubagentOverrides(projects: Project[]): Project[] {
  return projects.map((project) => {
    if (!project.overrides || !("subagents" in project.overrides)) return project;
    const subagents = sanitizeProjectSubagentSettings(project.overrides.subagents);
    const overrides = { ...project.overrides };
    if (subagents) overrides.subagents = subagents;
    else delete overrides.subagents;
    return { ...project, overrides: Object.keys(overrides).length ? overrides : undefined };
  });
}

/** Destinations that are switched on and currently usable. */
export function readyChildAgentTargets(
  settings: ChildAgentSettings,
  readiness: ChildAgentReadiness,
): ChildAgentTarget[] {
  return settings.targets.filter((target) => target.enabled && !childAgentTargetIssue(target, readiness));
}

export interface ChildAgentPolicyInput {
  sessionId: string;
  rootThreadId?: string;
  childAgents: ChildAgentSettings;
  subagentsEnabled: boolean;
  subagentMax: number;
  permission: PermissionMode;
  systemPrompt: string;
  projectInstructionsEnabled: boolean;
  reasoningEffort: ReasoningEffort;
  serviceTier: string | null;
  readiness: ChildAgentReadiness;
  now?: number;
}

/**
 * Freeze the delegation policy for a root thread. Returns null when nothing
 * should be exposed, which is also every pre-1.5 configuration: cross-provider
 * delegation rides on the existing sub-agent switch, so a user who never turns
 * on sub-agents sees exactly the behaviour they had before.
 */
export function childAgentPolicyFor(input: ChildAgentPolicyInput): ChildAgentPolicy | null {
  if (!input.subagentsEnabled || !input.childAgents.enabled) return null;
  const targets = readyChildAgentTargets(input.childAgents, input.readiness);
  if (!targets.length) return null;
  return {
    sessionId: input.sessionId,
    rootThreadId: input.rootThreadId ?? "",
    maxConcurrent: Math.min(MAX_SUBAGENT_CONCURRENCY, Math.max(1, Math.floor(input.subagentMax) || 1)),
    permission: input.permission,
    systemPrompt: input.systemPrompt,
    projectInstructionsEnabled: input.projectInstructionsEnabled,
    reasoningEffort: input.reasoningEffort,
    serviceTier: input.serviceTier,
    targets: targets.map((target) => ({ ...target })),
    capturedAt: input.now ?? Date.now(),
  };
}

/** The subset of a policy the backend session needs. Carries no secrets. */
export function childAgentSessionOptions(policy: ChildAgentPolicy, knownChildren: string[] = []): {
  sessionId: string;
  maxConcurrent: number;
  knownChildren: string[];
  targets: Array<{
    id: string;
    provider: string;
    model: string;
    label: string;
    description: string;
    reasoningMode: ChildAgentTarget["reasoningMode"];
    reasoningEffort: ReasoningEffort;
    reasoningMaxEffort: ReasoningEffort;
  }>;
} {
  return {
    sessionId: policy.sessionId,
    maxConcurrent: policy.maxConcurrent,
    knownChildren: [...knownChildren],
    targets: policy.targets.map((target) => ({
      id: target.id,
      provider: target.provider,
      model: childAgentModel(target),
      label: target.label,
      description: target.description,
      reasoningMode: target.reasoningMode,
      reasoningEffort: target.reasoningEffort,
      reasoningMaxEffort: target.reasoningMaxEffort,
    })),
  };
}

/** Rebuild the per-thread policies keyed by bridge session id. */
export function sanitizeChildAgentPolicies(stored: unknown): Record<string, ChildAgentPolicy> {
  if (!stored || typeof stored !== "object") return {};
  const result: Record<string, ChildAgentPolicy> = {};
  for (const [sessionId, candidate] of Object.entries(stored as Record<string, unknown>)) {
    if (!sessionId.trim() || sessionId.length > 64 || !candidate || typeof candidate !== "object") continue;
    const entry = candidate as Record<string, unknown>;
    const targets = sanitizeChildAgentSettings({ enabled: true, targets: entry.targets }).targets;
    if (!targets.length) continue;
    const permission = entry.permission;
    const reasoningEffort = entry.reasoningEffort;
    result[sessionId] = {
      sessionId,
      rootThreadId: typeof entry.rootThreadId === "string" ? entry.rootThreadId : "",
      maxConcurrent: Math.min(MAX_SUBAGENT_CONCURRENCY, Math.max(1, Math.floor(Number(entry.maxConcurrent)) || 1)),
      permission: permission === "read-only" || permission === "full" ? permission : "ask",
      systemPrompt: typeof entry.systemPrompt === "string" ? entry.systemPrompt : "",
      projectInstructionsEnabled: entry.projectInstructionsEnabled === true,
      reasoningEffort: reasoningEffort === "low" || reasoningEffort === "medium" || reasoningEffort === "high"
        || reasoningEffort === "xhigh" || reasoningEffort === "max" || reasoningEffort === "ultra"
        ? reasoningEffort
        : "medium",
      serviceTier: typeof entry.serviceTier === "string" ? entry.serviceTier : null,
      targets,
      capturedAt: Number(entry.capturedAt) || 0,
    };
  }
  return result;
}

/** The frozen policy a thread already owns, or undefined for a fresh thread. */
export function childAgentPolicyForThread(
  policies: Record<string, ChildAgentPolicy>,
  threadId: string | undefined,
): ChildAgentPolicy | undefined {
  if (!threadId) return undefined;
  return Object.values(policies).find((policy) => policy.rootThreadId === threadId);
}

export function sanitizeChildAgentLinks(stored: unknown): Record<string, ChildAgentLink> {
  if (!stored || typeof stored !== "object") return {};
  const result: Record<string, ChildAgentLink> = {};
  for (const [childThreadId, candidate] of Object.entries(stored as Record<string, unknown>)) {
    if (!childThreadId.trim() || !candidate || typeof candidate !== "object") continue;
    const entry = candidate as Record<string, unknown>;
    const provider = entry.provider as Provider;
    if (typeof entry.rootThreadId !== "string" || !entry.rootThreadId.trim()) continue;
    if (!CHILD_AGENT_PROVIDERS.includes(provider)) continue;
    const sessionId = sanitizeText(entry.sessionId, 64);
    const targetId = sanitizeText(entry.targetId, 40);
    if (!sessionId || !isValidChildAgentId(targetId)) continue;
    result[childThreadId] = {
      childThreadId,
      rootThreadId: entry.rootThreadId,
      sessionId,
      targetId,
      provider,
      model: sanitizeText(entry.model, 128),
      reasoningEffort: isReasoningEffort(entry.reasoningEffort) ? entry.reasoningEffort : "medium",
      title: sanitizeText(entry.title, 200),
      createdAt: Number(entry.createdAt) || 0,
      ...(entry.terminalStatus === "completed" || entry.terminalStatus === "cancelled" || entry.terminalStatus === "failed"
        ? { terminalStatus: entry.terminalStatus }
        : {}),
    };
  }
  return result;
}

/** One-line summary for the composer and settings, e.g. "3 destinations". */
export function describeChildAgentRoster(
  settings: ChildAgentSettings,
  readiness: ChildAgentReadiness,
): string {
  if (!settings.enabled) return "Cross-provider off";
  const ready = readyChildAgentTargets(settings, readiness).length;
  const enabled = settings.targets.filter((target) => target.enabled).length;
  if (!enabled) return "No destinations";
  if (!ready) return "No destination ready";
  return ready === enabled ? `${ready} destination${ready === 1 ? "" : "s"}` : `${ready} of ${enabled} ready`;
}

/** Starting points offered in Settings so the roster is never a blank page. */
export const SUGGESTED_CHILD_AGENT_TARGETS: Array<Omit<ChildAgentTarget, "enabled">> = [
  { id: "openai", provider: "openai", model: "", label: "OpenAI", description: "General implementation and refactoring on the ChatGPT subscription.", reasoningMode: "inherit", reasoningEffort: "medium", reasoningMaxEffort: "high" },
  { id: "claude", provider: "claude", model: "", label: "Claude Code", description: "Careful review, long-context reasoning, and test writing.", reasoningMode: "inherit", reasoningEffort: "medium", reasoningMaxEffort: "high" },
  { id: "cursor", provider: "cursor", model: "auto", label: "Cursor", description: "Fast in-repo edits through the Cursor subscription.", reasoningMode: "inherit", reasoningEffort: "medium", reasoningMaxEffort: "high" },
  { id: "openrouter", provider: "openrouter", model: "", label: "OpenRouter", description: "A specific third-party model routed through OpenRouter.", reasoningMode: "inherit", reasoningEffort: "medium", reasoningMaxEffort: "high" },
];
