import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { invoke } from "@tauri-apps/api/core";
import { ProjectRunControl } from "./ProjectRunControl";
import { loadStored } from "../lib/storage";
import { DISCOVERY_PROVIDERS, RUN_DISCOVERY_PREFERENCES_KEY } from "../lib/runDiscovery";
vi.mock("@tauri-apps/api/core", () => ({ invoke: vi.fn() }));
beforeEach(() => { vi.mocked(invoke).mockReset(); localStorage.clear(); });
it("finds and saves the command while closed without launching it", async () => {
  let finish!: (value: unknown) => void;
  vi.mocked(invoke).mockImplementation(() => new Promise((resolve) => { finish = resolve; }));
  const onSave = vi.fn(), onRun = vi.fn();
  render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" running={false} onRun={onRun} onStop={vi.fn()} onSave={onSave} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Find run command" }));
  expect(screen.getByRole("textbox", { name: "Run command for Alpha" })).toBeDisabled();
  expect(screen.getByRole("button", { name: "Save run command" })).toBeDisabled();
  fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
  await act(async () => finish({ command: ".venv/bin/python main.py", label: "Dev game", explanation: "Uses the installed project environment." }));
  expect(onSave).toHaveBeenCalledExactlyOnceWith({ command: ".venv/bin/python main.py", label: "Dev game" });
  expect(onRun).not.toHaveBeenCalled();
  expect(vi.mocked(invoke)).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  expect(await screen.findByText("Saved to Run")).toBeInTheDocument();
});
it("stopping or navigating never saves a late result to either project", async () => {
  let finish!: (value: unknown) => void;
  vi.mocked(invoke).mockImplementation((name) => name === "run_discovery_start" ? new Promise((resolve) => { finish = resolve; }) : Promise.resolve());
  const onSave = vi.fn();
  const { rerender } = render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={onSave} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Find run command" }));
  fireEvent.click(screen.getByRole("button", { name: "Stop discovery" }));
  await act(async () => finish({ command: "old command", label: "Old", explanation: "Stopped" }));
  expect(onSave).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Find run command" }));
  rerender(<ProjectRunControl projectName="Beta" projectPath="/beta" running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={onSave} />);
  await act(async () => finish({ command: "wrong project", label: "Old", explanation: "Late" }));
  expect(onSave).not.toHaveBeenCalled();
});
it("persists model settings and passes Fast with the selected live model effort", async () => {
  vi.mocked(invoke).mockRejectedValue(new Error("Fixture offline"));
  render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" discoveryCatalogs={{ openai: [{ id: "gpt-5.6-luna", label: "Luna", efforts: ["low", "high"] }] }} running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Discovery model settings" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Fast mode (priority service)" }));
  expect(loadStored(RUN_DISCOVERY_PREFERENCES_KEY, null)).toMatchObject({ model: "gpt-5.6-luna", fast: false });
  fireEvent.click(screen.getByRole("button", { name: "Find run command" }));
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("Fixture offline"));
  expect(vi.mocked(invoke)).toHaveBeenCalledWith("run_discovery_start", { options: expect.objectContaining({ model: "gpt-5.6-luna", effort: "high", fast: false }) });
  expect(screen.getByRole("button", { name: "Find run command" })).toBeEnabled();
});
it("Escape dismisses only a nested menu and a saved result survives accidental close", async () => {
  vi.mocked(invoke).mockResolvedValue({ command: "npm run dev", label: "Dev server", explanation: "Package script" });
  render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" discoveryCatalogs={{ openai: [{ id: "gpt-5.6-luna", label: "Luna" }] }} running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Discovery model settings" }));
  fireEvent.change(screen.getByRole("textbox", { name: "Run command for Alpha" }), { target: { value: "manual edit" } });
  fireEvent.click(screen.getByRole("button", { name: "Discovery model" }));
  expect(screen.getByRole("menu")).toBeInTheDocument();
  fireEvent.keyDown(document, { key: "Escape" });
  expect(screen.queryByRole("menu")).not.toBeInTheDocument();
  expect(screen.getByRole("textbox", { name: "Run command for Alpha" })).toHaveValue("manual edit");
  fireEvent.click(screen.getByRole("button", { name: "Find run command" }));
  await screen.findByText("Saved to Run");
  fireEvent.keyDown(document, { key: "Escape" });
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  expect(await screen.findByText("Saved to Run")).toBeInTheDocument();
  expect(vi.mocked(invoke)).toHaveBeenCalledOnce();
});

it.each(DISCOVERY_PROVIDERS)("routes discovery through $label with only supported controls", async ({ value: provider, label }) => {
  vi.mocked(invoke).mockResolvedValue({ command: "npm run dev", label: "Dev", explanation: "Manifest" });
  const onAccounts = vi.fn();
  const catalog = Object.fromEntries(DISCOVERY_PROVIDERS.map(({ value }) => [value, [{ id: `${value}-model`, label: `${value} model`, efforts: value === "openai" ? ["minimal", "high"] : value === "claude" ? ["low", "high"] : [] }]]));
  render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" lmStudioBaseUrl="http://localhost:4567/v1" discoveryCatalogs={catalog} onDiscoveryAccounts={onAccounts} running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Discovery model settings" }));
  fireEvent.click(screen.getByRole("button", { name: "Discovery provider" }));
  expect(screen.getAllByRole("menuitemradio")).toHaveLength(5);
  fireEvent.click(screen.getByRole("menuitemradio", { name: label }));
  fireEvent.click(screen.getByRole("button", { name: "Discovery model" }));
  fireEvent.click(screen.getByRole("menuitemradio", { name: `${provider} model` }));
  expect(Boolean(screen.queryByRole("checkbox", { name: "Fast mode (priority service)" }))).toBe(provider === "openai");
  expect(Boolean(screen.queryByRole("button", { name: "Discovery reasoning" }))).toBe(provider === "openai" || provider === "claude");
  fireEvent.click(screen.getByRole("button", { name: "Models and accounts" }));
  expect(onAccounts).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "Find run command" }));
  await screen.findByText("Saved to Run");
  expect(invoke).toHaveBeenCalledWith("run_discovery_start", { options: expect.objectContaining({ provider, model: `${provider}-model`, fast: provider === "openai", effort: provider === "openai" ? "high" : provider === "claude" ? "low" : "default", ...(provider === "lmstudio" ? { lmStudioBaseUrl: "http://localhost:4567/v1" } : {}) }) });
});
it("edits custom model IDs without persisting each keystroke", async () => {
  vi.mocked(invoke).mockRejectedValue(new Error("Offline"));
  render(<ProjectRunControl projectName="Alpha" projectPath="/alpha" running={false} onRun={vi.fn()} onStop={vi.fn()} onSave={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: "Edit run command" }));
  fireEvent.click(await screen.findByRole("button", { name: "Discovery model settings" }));
  const input = screen.getByRole("textbox", { name: "Discovery model ID" });
  fireEvent.change(input, { target: { value: "my-model" } });
  expect(loadStored(RUN_DISCOVERY_PREFERENCES_KEY, null)).toBeNull();
  fireEvent.blur(input);
  expect(loadStored(RUN_DISCOVERY_PREFERENCES_KEY, null)).toMatchObject({ model: "my-model" });
  fireEvent.click(screen.getByRole("button", { name: "Find run command" }));
  await screen.findByRole("alert");
  expect(screen.getByRole("button", { name: "Edit run command" })).toHaveAttribute("title", "Discovery failed — open for details");
});
